### ISSUE TITLE
Implement Sorted Linked List.

### ISSUE THREAD

**Issue by happy-san** [code-shoily/algorithms-in-dart#10]
This will be similar to SinglyLinkedList. The differences would be:

- [fromList()](https://github.com/code-shoily/algorithms-in-dart/blob/6205143ee913d90f8108104e4eef979561648f8a/lib/lists/singly_linked_list.dart#L36) constructor will sort the elements of the `list` before inserting them.

- [append()](https://github.com/code-shoily/algorithms-in-dart/blob/6205143ee913d90f8108104e4eef979561648f8a/lib/lists/singly_linked_list.dart#L98) won't be implemented.

- [insert()](https://github.com/code-shoily/algorithms-in-dart/blob/6205143ee913d90f8108104e4eef979561648f8a/lib/lists/singly_linked_list.dart#L114) will not take position as parameter, since we'll decide where the `newNode` goes.

**Comment by Omeiza17** [comment]
Hi, I will like to wok on this issue. Can you assign it to me?

**Comment by happy-san** [comment]
@Omeiza17 feel free to reach out if you're stuck/ need help!

**Comment by happy-san** [comment]
@Omeiza17 Please report the progress, if you're not working on this issue, I'll unassign it.
