### ISSUE TITLE
Add function to balance height of the binary tree

### ISSUE THREAD

**Issue by happy-san** [code-shoily/algorithms-in-dart#5]
Hey, @code-shoily would a balance function be good addition to BinaryTree class? I can open PR.

**Comment by code-shoily** [comment]
Go ahead! I was going to implement AVL and Red Black Tree later any way but
adding a balance function would be good now too

**Comment by happy-san** [comment]
hey, [here](https://github.com/code-shoily/algorithms-in-dart/blob/d923c218103238987b8db113acd4b8c13c6f207d/test/trees/binary_test.dart#L141) `  });` is missing, my bad :3
